"""Load a catalogue dump into the PostgreSQL `catalogue` schema, in-process.

Streams each source's records into a staging table with `COPY`, then calls
`catalogue.load_record` over it. That avoids quoting six thousand JSON literals
into a script and is an order of magnitude faster than one statement per record.

Four things changed when this stopped shelling out to `psql` (§5.3), and each
was a real problem rather than a style preference:

* **No `psql` on PATH.** The loader could not run inside the worker's image,
  which is why the load was a separate manual step joined to the scrape by files
  on disk.
* **Real parameters.** The run id and the source name used to be spliced in with
  `RETIRE.replace("%(source)s", f"'{source}'")`. Source ids come from a
  checked-in file so it was not an injection surface, but it is now impossible
  for it to become one.
* **One transaction per source**, covering stage, `load_record`, retire-unseen
  and truncate. A crash between the four `psql` invocations used to leave
  staging populated and retirement half-applied, with the source counted as
  loaded.
* **A temporary staging table per connection**, not one shared unlogged table.
  This is required by concurrency, not optional: two workers loading at once
  would otherwise stage into each other's rows and retire against the union —
  which, for two sources, retires everything each of them did not list.

`plan_load` and `authoritative` are unchanged, deliberately and to the letter.
They are the load's safety property — an empty file is never grounds for
retirement, a partial file only ever adds, a truncated run is adds-only — and
`tests/test_load_planning.py` pins every one of them.
"""

from __future__ import annotations

import gzip
import json
from collections.abc import Iterable, Iterator
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any
from uuid import UUID

import psycopg

from mb_ceramics_catalogue.observability import logging as obs
from mb_ceramics_catalogue.observability import metrics

LOGGER = obs.get_logger("catalogue.load")

Connection = psycopg.Connection[dict[str, Any]]

# A temporary table, so two workers loading at once cannot see each other's
# rows. Created once per connection and truncated per source; `on commit drop`
# would take it away between sources.
CREATE_STAGING = """
create temporary table if not exists import_staging (
  line_number bigint generated by default as identity,
  source_file text,
  record jsonb
) on commit preserve rows
"""

LOAD = """
select catalogue.load_record(record, %(run)s::uuid)
  from import_staging
 order by line_number
"""

# The same call for one staged row, used only after the set-based one has
# failed. `catalogue.load_record` enforces real invariants — a price with no
# currency, a quantity with no unit — and raises on the row that breaks one.
# Raising is right; what was wrong is that it happened inside a single statement
# covering the whole source, so one unpriceable variant discarded every other
# record with it. On 2026-08-11 that cost art-academy-direct all 4,980 of its
# rows, and gwn-pottery and sheffield-pottery a run each in the days before.
LOAD_ONE = """
select catalogue.load_record(record, %(run)s::uuid)
  from import_staging
 where line_number = %(line)s
"""

STAGED_LINES = "select line_number from import_staging order by line_number"

#: Rejected rows quoted in the report. Enough to see the shape of the problem;
#: a source where every row is rejected does not need six thousand copies of it.
REJECT_SAMPLE = 5

RETIRE = """
update catalogue.source_products p
   set active = false
 where p.source_id = %(source)s
   and p.active
   and not exists (
     select 1 from import_staging s
      where s.record->>'external_id' = p.external_id
   )
"""

# `catalogue.load_record` creates a source row from the id alone, because a
# record carries no description of the shop it came from. Everything a reader
# needs to tell one supplier from another — the name to print, the shop it
# points at, the country it ships from — is in sources.json, so it is copied
# across here.
DESCRIBE = """
insert into catalogue.sources (id, label, homepage_url, metadata)
values (%(id)s, %(label)s, %(url)s, %(metadata)s::jsonb)
on conflict (id) do update
   set label = coalesce(excluded.label, catalogue.sources.label),
       homepage_url = coalesce(excluded.homepage_url, catalogue.sources.homepage_url),
       -- Merged rather than replaced: this file is not the only thing that has
       -- an opinion about a source, and it should not drop what it never set.
       metadata = catalogue.sources.metadata || excluded.metadata,
       updated_at = now()
"""


# ---------------------------------------------------------------------------
# Planning: which file, and whether it may be treated as a whole catalogue
# ---------------------------------------------------------------------------


def records_in(path: Path) -> int:
    """How many records a dump file holds, ignoring blank lines."""
    if not path.exists():
        return 0
    opener = gzip.open if path.name.endswith(".gz") else open
    with opener(path, "rt", encoding="utf-8") as handle:
        return sum(1 for line in handle if line.strip())


class Load:
    """One source's contribution to a load: which file, and whether it is whole.

    `whole` is what decides retirement. A complete dump is the entirety of a
    supplier's catalogue, so anything of theirs it does not list has been
    withdrawn. A `.partial.ndjson` is a run that stopped early, which is not a
    smaller catalogue but an unfinished one — retiring against it would withdraw
    products that are still for sale and never appeared in the file only because
    nobody got that far.
    """

    def __init__(self, source: str, path: Path, whole: bool, records: int) -> None:
        self.source = source
        self.path = path
        self.whole = whole
        self.records = records

    def __repr__(self) -> str:  # pragma: no cover - diagnostics only
        return f"<Load {self.source} {self.records} records {'whole' if self.whole else 'adds-only'}>"


def plan_load(data: Path) -> tuple[list[Load], list[tuple[str, str]]]:
    """Choose one file per source, and say what was left out and why.

    Three things in a dump directory must not be treated as a catalogue:

    - An **empty** `<source>.ndjson`. A scrape that collected nothing says
      nothing about what the shop sells, but loading it and then retiring
      against it would mark that supplier's every product withdrawn. Seven
      suppliers in the v3 dump are in exactly this state.
    - A **partial** file for a source whose complete file has records. The
      complete file is the newer and fuller account; replaying the leftovers of
      an interrupted attempt over it would re-activate rows the complete dump
      had just retired.
    - A **partial** file as grounds for retirement. It is loaded when it is all
      there is, but only ever adds.
    """
    # The dump tool records, per source, whether this run actually wrote the file
    # and whether it stopped at a cap. Both bear on retirement, and neither is
    # visible from the filename. An older dump directory without a manifest keeps
    # the previous behaviour: a complete file is taken at face value.
    manifest: dict[str, dict] = {}
    manifest_path = data / "manifest.json"
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8")).get("sources", {})

    def authoritative(source: str) -> tuple[bool, str]:
        """Whether a complete file may be read as the whole of a catalogue."""
        if not manifest:
            return True, ""
        entry = manifest.get(source)
        if entry is None:
            return False, "no manifest entry for this run"
        return may_retire(entry.get("write_status"), entry.get("truncated"))

    plans: list[Load] = []
    skipped: list[tuple[str, str]] = []
    suffixes = (".partial.ndjson.gz", ".partial.ndjson", ".ndjson.gz", ".ndjson")
    names = sorted(
        {
            next(path.name[: -len(suffix)] for suffix in suffixes if path.name.endswith(suffix))
            for path in data.iterdir()
            if path.is_file() and any(path.name.endswith(suffix) for suffix in suffixes)
        }
    )
    for source in names:
        complete = next(
            (path for path in (data / f"{source}.ndjson.gz", data / f"{source}.ndjson") if path.exists()),
            data / f"{source}.ndjson.gz",
        )
        partial = next(
            (
                path
                for path in (data / f"{source}.partial.ndjson.gz", data / f"{source}.partial.ndjson")
                if path.exists()
            ),
            data / f"{source}.partial.ndjson.gz",
        )
        whole, half = records_in(complete), records_in(partial)
        if whole:
            trusted, why = authoritative(source)
            plans.append(Load(source, complete, trusted, whole))
            if not trusted:
                skipped.append((source, f"loaded as adds-only: {why}"))
            if half:
                skipped.append((source, f"{half} partial records, superseded by a complete dump"))
        elif half:
            plans.append(Load(source, partial, False, half))
        else:
            skipped.append((source, "no records in this dump"))
    return plans, skipped


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


@dataclass
class SourceReport:
    """What loading one source did."""

    source: str
    records: int = 0
    retired: int = 0
    error: str | None = None
    #: Rows `catalogue.load_record` refused. The rest of the source still
    #: loaded; see `LOAD_ONE`.
    rejected: int = 0
    #: Why, for the first few. One line each, for the run summary and the job log.
    rejects: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.error is None


@dataclass
class LoadReport:
    """What a whole load did, so a caller can print it and CI can assert on it."""

    run_id: UUID | None = None
    sources: list[SourceReport] = field(default_factory=list)
    products: int = 0
    offers: int = 0
    identities: int = 0

    @property
    def loaded(self) -> list[SourceReport]:
        return [report for report in self.sources if report.ok]

    @property
    def failures(self) -> list[SourceReport]:
        return [report for report in self.sources if not report.ok]

    @property
    def ok(self) -> bool:
        return not self.failures

    @property
    def records(self) -> int:
        return sum(report.records for report in self.loaded)


def may_retire(write_status: Any, truncated: Any) -> tuple[bool, str]:
    """Whether one source's collection may be read as the whole of a catalogue.

    The one rule that decides whether products get withdrawn, in one place
    because it has two callers that must never disagree. `plan_load` asks it of
    a manifest entry; the worker asks it of the source it has just collected.

    They *did* disagree. `plan_load` has refused to retire against a truncated
    dump since the day the flag was added, and the worker — which is what runs
    every night — decided `whole` from the artifact's write status alone and
    never looked at `truncated` at all. So the safety property the README
    states, the tests pin and the scrapers are careful to feed had no effect on
    the only path that uses it in production. On 2026-08-10 that retired 24,856
    products across seventeen sources; ceram-decor is still short 543 of 758
    because its dumps keep being truncated and each run withdraws what the last
    one could not read.
    """
    if write_status != "replaced":
        # 'preserved_existing_nonempty' is the dangerous one: the run wrote
        # nothing and an older file was left in place. It looks complete and
        # is not, and retiring against it withdraws a live catalogue.
        return False, f"write_status {write_status!r}, not written by this run"
    if truncated:
        return False, "run hit its cap, so the file is not the whole catalogue"
    return True, ""


def ensure_staging(connection: Connection) -> None:
    """Create this connection's private staging table."""
    with connection.cursor() as cursor:
        cursor.execute(CREATE_STAGING)


def _load_staged(
    connection: Connection, cursor: Any, report: SourceReport, run_id: UUID | None
) -> None:
    """Load every staged row, and let a row the database refuses cost only itself.

    The fast path is unchanged and is what nearly every source takes: one
    statement, one `load_record` call per row, no round trip per record. It runs
    inside a savepoint so that failing does not poison the transaction the
    caller is holding — which still has the retire step to do.

    Only when that statement fails is the source re-loaded a row at a time, each
    under its own savepoint, so the rows that are fine land and the ones that
    are not are counted and named. It is a round trip per record and it is only
    ever paid by a source that has something wrong with it.

    Rejected rows stay in staging deliberately. Retirement asks "what did this
    dump not list", and a row we failed to load was still listed — dropping it
    from the question would retire a product the shop still sells.
    """
    try:
        with connection.transaction():
            cursor.execute(LOAD, {"run": run_id})
        return
    except psycopg.Error as error:
        LOGGER.warning(
            "load.batch_refused",
            source=report.source,
            error=_reason(error),
            detail="reloading one record at a time",
        )

    cursor.execute(STAGED_LINES)
    for line in [row["line_number"] for row in cursor.fetchall()]:
        try:
            with connection.transaction():
                cursor.execute(LOAD_ONE, {"run": run_id, "line": line})
        except psycopg.Error as error:
            report.rejected += 1
            if len(report.rejects) < REJECT_SAMPLE:
                report.rejects.append(f"line {line}: {_reason(error)}")

    if report.rejected:
        LOGGER.warning(
            "load.records_refused",
            source=report.source,
            rejected=report.rejected,
            of=report.records,
            reasons=report.rejects,
        )


def _reason(error: psycopg.Error) -> str:
    """The first line of a database error: the condition, without the context."""
    return str(error).strip().splitlines()[0] if str(error).strip() else error.__class__.__name__


def read_ndjson(path: Path) -> Iterator[dict[str, Any]]:
    """Yield each record in a dump file, skipping blank lines.

    A generator rather than a list: the whole point of `COPY` here is that a
    4,473-record source streams through without both the file and the parsed
    records being resident at once.
    """
    opener = gzip.open if path.name.endswith(".gz") else open
    with opener(path, "rt", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                yield json.loads(line)


def load_source(
    connection: Connection,
    source: str,
    records: Iterable[dict[str, Any]],
    *,
    whole: bool,
    run_id: UUID | None = None,
    stock_trends_enabled: bool = False,
) -> SourceReport:
    """Stage, load and (if the file is whole) retire, in one transaction.

    Either all four steps happen for this source or none do. That is the point
    of the rewrite: the previous four separate `psql` invocations could be
    interrupted between any two, leaving staging populated, retirement
    half-applied, and the source counted as loaded.

    Retirement is asked of the staged rows rather than of a timestamp.
    `last_seen_at` carries the moment the *page* was fetched, which is always
    older than the load, so a clock comparison retires the entire source.
    """
    report = SourceReport(source=source)

    with connection.transaction(), connection.cursor() as cursor:
        # A transaction-local custom setting lets the database function keep
        # raw records intact while gating only relational stock history. It
        # cannot leak through a pooled connection after this source commits.
        cursor.execute(
            "select set_config('catalogue.stock_trends_enabled', %(enabled)s, true)",
            {"enabled": "true" if stock_trends_enabled else "false"},
        )
        cursor.execute("truncate import_staging")

        # One row per record, the JSON sent as text. Binary would need the jsonb
        # type oid and buys nothing: the cost of this load is the `load_record`
        # call per row, not the parse.
        with cursor.copy("copy import_staging (source_file, record) from stdin") as copy:
            for record in records:
                copy.write_row((source, json.dumps(record, ensure_ascii=False, default=str)))
                report.records += 1

        _load_staged(connection, cursor, report, run_id)

        if whole:
            # Asked while this file is still staged, so "not in the dump" is a
            # question about the dump itself. Only a complete dump is grounds
            # for it, which is why `whole` is a parameter decided by `plan_load`
            # rather than something inferred here from a filename.
            cursor.execute(RETIRE, {"source": source})
            report.retired = max(cursor.rowcount, 0)

        cursor.execute("truncate import_staging")

    metrics.offers_written(report.records)
    LOGGER.info(
        "load.source",
        source=source,
        records=report.records,
        rejected=report.rejected,
        retired=report.retired,
        whole=whole,
    )
    return report


def describe_sources(
    connection: Connection, sources: dict[str, dict[str, Any]], only: set[str] | None = None
) -> int:
    """Copy each source's identity from sources.json into catalogue.sources."""
    written = 0
    with connection.cursor() as cursor:
        for source_id, config in sorted(sources.items()):
            if only is not None and source_id not in only:
                continue
            # Only the keys that describe the shop; the scraper settings beside
            # them are the crawler's business and would be noise in a reporting
            # database.
            metadata = {key: config[key] for key in ("country", "scope") if config.get(key)}
            cursor.execute(
                DESCRIBE,
                {
                    "id": source_id,
                    "label": config.get("label"),
                    "url": config.get("url"),
                    "metadata": json.dumps(metadata, sort_keys=True),
                },
            )
            written += 1
    return written


def load_dump(
    connection: Connection,
    plans: list[Load],
    sources: dict[str, dict[str, Any]],
    described: set[str],
    *,
    keep_stale: bool = False,
    run_id: UUID | None = None,
    stock_trends_enabled: bool = False,
) -> LoadReport:
    """Load every planned source, stepping over the ones that fail.

    One source failing is one supplier's data, not the load's. A record the
    schema rejects — a price with no currency, say — used to abort everything
    after it, so a defect in the third of sixty-three sources cost the other
    sixty. Each source is its own transaction, and a failure is recorded and
    stepped over, with the import run marked failed at the end so that nothing
    looks clean that was not.
    """
    report = LoadReport()
    ensure_staging(connection)

    with connection.cursor() as cursor:
        cursor.execute(
            "insert into catalogue.import_runs (status, importer_version, run_id) "
            "values ('running', %(version)s, %(run)s) returning id",
            {"version": "mb_ceramics_catalogue.storage.postgres", "run": run_id},
        )
        row = cursor.fetchone()
        assert row is not None
        report.run_id = row["id"]

    describe_sources(connection, sources, described)

    for plan in plans:
        try:
            report.sources.append(
                load_source(
                    connection,
                    plan.source,
                    read_ndjson(plan.path),
                    whole=plan.whole and not keep_stale,
                    run_id=report.run_id,
                    stock_trends_enabled=stock_trends_enabled,
                )
            )
        except (psycopg.Error, json.JSONDecodeError) as failure:
            # The server's complaint, not a traceback: it is the line that says
            # which part of the record the dump got wrong. The transaction has
            # already rolled back, so staging is clean for the next source.
            text = str(failure).strip()
            reason = text.splitlines()[0] if text else "unknown error"
            report.sources.append(SourceReport(source=plan.source, error=reason[:500]))
            LOGGER.warning("load.source_failed", source=plan.source, error=reason)

    with connection.cursor() as cursor:
        cursor.execute(
            "update catalogue.import_runs set status = %(status)s, finished_at = now(), "
            "record_count = %(count)s where id = %(id)s",
            {
                "status": "failed" if report.failures else "complete",
                "count": report.records,
                "id": report.run_id,
            },
        )
        cursor.execute(
            "select (select count(*) from catalogue.source_products) as products,"
            " (select count(*) from catalogue.offer_observations) as offers,"
            " (select count(*) from catalogue.source_products"
            "   where record_format like '%%identity%%') as identities"
        )
        totals = cursor.fetchone()
        assert totals is not None
        report.products = int(totals["products"])
        report.offers = int(totals["offers"])
        report.identities = int(totals["identities"])

    return report
